print("In the Quadratic equation\na(x^2)+bx+c, Enter such values")
a=float(input("Enter the value of 'a' : "))
b=float(input("Enter the value of 'b' : "))
c=float(input("Enter the value of 'c' : "))
d=((b*b)-(4*a*c))**(1/2)
x1=(-b+d)/(2*a)
x2=(-b-d)/(2*a)
print("roots of the equation are")
print("x=",x1," x=",x2)
